Repository CarpoolMATE/FRONTEND, pull requests merged in 2025-02, with the labels that each got.

#2 [Design] 레이아웃 UI 변경
  public/fonts/AppleSDGothicNeo.ttf
  src/app/(auth)/sign-in/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/RootLayout.tsx
Labels: refector

#7 [Fix] placehold 이미지 경로 변경
  next.config.ts
  src/app/(client)/home/page.tsx
  src/app/(client)/layout.tsx
  src/app/admin/promiseDetail/page.tsx
  src/app/admin/userDetail/page.tsx
  src/app/detailCarple/page.tsx
  src/app/profile/edit/page.tsx
  src/app/profile/page.tsx
  src/app/registerCarple/fourthStep/page.tsx
Labels: bug

#9 [Fix] searchParams에 Suspense 사용
  src/app/(auth)/find-id/result/components/MemberInfo/index.tsx
  src/app/(auth)/find-id/result/page.tsx
  src/components/Spin/index.tsx
Labels: enhancement

#17 Fix : 회원가입 및 비밀번호 찾기 요청 후 라우팅을 home > login page로 변경했습니다.
  src/app/(auth)/find-password/components/Form/index.tsx
  src/app/(auth)/sign-up/page.tsx
Labels: enhancement, chore

#27 Fix: 파일 업로드 API 로직 수정
  src/apis/fetch.ts
  src/apis/postUpload.ts
  src/apis/types.ts
Labels: enhancement
