Repository CarpoolMATE/FRONTEND, pull requests merged in 2025-03, with the labels that each got.

#43 [Fix] next auth secret 설정
  src/app/api/auth/[...nextauth]/route.ts
Labels: bug

#45 Feat : profile page logout 기능 추가
  src/app/(client)/profile/page.tsx
Labels: enhancement, feature

#48 Fix : 회원가입 ui 깨짐 현상을 수정했습니다.
  src/app/(auth)/sign-up/page.tsx
Labels: bug, enhancement

#50 [Fix] 드라이버 등록 - 이미지 업로드 로직 변경
  src/app/(client)/driver-registration/components/CarImage/index.tsx
  src/app/(client)/driver-registration/components/Form/schema.ts
  src/app/(client)/driver-registration/components/PhoneNumber/index.tsx
  src/constants/common.ts
Labels: bug

#51 Fix : 회원가입시 비밀번호와 비밀번호 확인의 인풋값이 같은지 확인 로직을 버튼에 추가했습니다.
  src/app/(auth)/sign-up/page.tsx
Labels: bug, enhancement

#53 [Release] 2025.03.28
  package-lock.json
  package.json
  src/app/(auth)/sign-up/page.tsx
  src/app/(client)/driver-registration/components/CarImage/index.tsx
  src/app/(client)/driver-registration/components/Form/schema.ts
  src/app/(client)/driver-registration/components/PhoneNumber/index.tsx
  src/app/(client)/profile/driver-edit/page.tsx
  src/app/(client)/profile/passenger-edit/page.tsx
  src/components/Image/Upload/CropModal.tsx
  src/components/Image/Upload/index.tsx
  src/components/Image/Upload/types.ts
  src/constants/common.ts
Labels: release
